site_name: Tips de Cristo

nav:
  - Contenido: 'index.md'
  - Code:
    - Devops:
      - Ansible: 'code/devops/ansible/ansible.md'
      - Docker:
        - Aclaraciones: 'code/devops/docker/docker-aclaraciones.md'
        - Instalaci칩n: 'code/devops/docker/docker-instalacion.md'
        - Docker Hub: 'code/devops/docker/docker-hub.md'
        - Comandos docker: 'code/devops/docker/docker-comandos.md'
        - Lanzar contenedores: 'code/devops/docker/docker-contenedores.md'
        - Crear im치genes: 'code/devops/docker/docker-imagenes.md'
        - Dockerfile: 'code/devops/docker/docker-dockerfile.md'
        - Volumes: 'code/devops/docker/docker-volumes.md'
        - Network: 'code/devops/docker/docker-network.md'
        - Docker Compose: 'code/devops/docker/docker-dockercompose.md'
      - Git: 'code/devops/git/git-git.md'
      - Git Flow:
          - Git Flow: 'code/devops/git/gitflow/gitflow-gitflow.md'
          - Puesta a punto: 'code/devops/git/gitflow/gitflow-instalacion.md'
          - Comandos: 'code/devops/git/gitflow/gitflow-comandos.md'
    - IDEs:
      - Visual Studio code: 'code/ides/vscode/vscode.md'
    - Python:
      - Entornos virtuales:
        - Introducci칩n: 'code/python/venv/venv-introduccion.md'
        - virtualenv: 'code/python/venv/venv-virtualenv.md'
        - virtualenvwrapper: 'code/python/venv/venv-virtualenvwrapper.md'
        - pipenv: 'code/python/venv/venv-pipenv.md'
        - pyenv: 'code/python/venv/venv-pyenv.md'
      - PYTHONPATH: 'code/python/python-pythonpath.md'
    - Web:
      - Frontend:
        - HTML: 'code/web/frontend/html/html-indice.md'
        - CSS:
          - Plugins: 'code/web/frontend/css/css-plugins.md'
        - JS: 'code/web/frontend/js/js-indice.md'
      - Backend:
        - Django:
          - Django: 'code/web/backend/django/django.md'
          - Principiante: 'code/web/backend/django/django-principiante.md'
          - Intermedio: 'code/web/backend/django/django-intermedio.md'
  - Software:
    - Linux:
      - Fecha y Hora: 'sw/linux/linux-fecha-hora.md'
      - Ficheros: 'sw/linux/linux-ficheros.md'
    - Redes:
      - Linux: 'sw/redes/redes-linux.md'
      - SSH: 'sw/redes/redes-ssh.md'
      - iptables: 'sw/redes/redes-iptables.md'
      - IPv6: 'sw/redes/redes-ipv6.md'
    - Terminal:
      - tmux: 
        - Comandos: 'sw/terminal/tmux/tmux-comandos.md'
        - Customizaci칩n: 'sw/terminal/tmux/tmux-customizar.md'
      - ZSH: 'sw/terminal/terminal-zsh.md'
  - Hardware:
    - Micropython: 'hw/upython/upython-informacion.md'
    - Platformio: 'hw/pio/pio-informacion.md'
  - IoT:
    - MQTT:
      - MQTT: 'iot/mqtt/mqtt.md'
      - Hola mundo: 'iot/mqtt/mqtt-hello-world.md'
theme:
  #name: mkdocs
  #name: readthedocs
  #name: rtd-dropdown
  #name: material
  name: windmill
