# 1. Información del Taller
site_name: Tips de Cristo
site_description: Apuntes de fácil acceso para distintas tecnologías.
site_author: Cristóbal Contreras Rubio
site_url: https://crisconru.github.io/

# 2. Repositorio
repo_name: crisconru/tips
repo_url: https://github.com/crisconru/tips
edit_uri: ""

# 3. Copyright
copyright: Copyright &copy; 2019 Cristóbal Contreras

# 4. RRSS
extra:
  social:
    - type: github
      link: https://github.com/crisconru
    - type: twitter
      link: https://twitter.com/crisconru
    - type: linkedin
      link: https://linkedin.com/in/cristobalcontrerasrubio

# 5. Navegación
nav:
  - Contenido: 'index.md'
  - Code:
    - Devops:
      - Ansible:
        - Ansible: 'code/devops/ansible/ansible.md'
        - Inventario: code/devops/ansible/inventario.md
      - Docker:
        - Aclaraciones: 'code/devops/docker/docker-aclaraciones.md'
        - Instalación: 'code/devops/docker/docker-instalacion.md'
        - Docker Hub: 'code/devops/docker/docker-hub.md'
        - Comandos docker: 'code/devops/docker/docker-comandos.md'
        - Lanzar contenedores: 'code/devops/docker/docker-contenedores.md'
        - Crear imágenes: 'code/devops/docker/docker-imagenes.md'
        - Dockerfile: 'code/devops/docker/docker-dockerfile.md'
        - Volumes: 'code/devops/docker/docker-volumes.md'
        - Network: 'code/devops/docker/docker-network.md'
        - Docker Compose: 'code/devops/docker/docker-dockercompose.md'
      - ELK:
        - code/devops/elk/elk.md
      - Git: 'code/devops/git/git-git.md'
      - Git Flow:
          - Git Flow: 'code/devops/git/gitflow/gitflow-gitflow.md'
          - Puesta a punto: 'code/devops/git/gitflow/gitflow-instalacion.md'
          - Comandos: 'code/devops/git/gitflow/gitflow-comandos.md'
    - IDEs:
      - Visual Studio code: 'code/ides/vscode/vscode.md'
    - Python:
      - Entornos virtuales:
        - Introducción: 'code/python/venv/venv-introduccion.md'
        - virtualenv: 'code/python/venv/venv-virtualenv.md'
        - virtualenvwrapper: 'code/python/venv/venv-virtualenvwrapper.md'
        - pipenv: 'code/python/venv/venv-pipenv.md'
        - pyenv: 'code/python/venv/venv-pyenv.md'
      - PYTHONPATH: 'code/python/python-pythonpath.md'
    - Web:
      - Frontend:
        - HTML: 'code/web/frontend/html/html-indice.md'
        - CSS:
          - Plugins: 'code/web/frontend/css/css-plugins.md'
        - JS: 'code/web/frontend/js/js-indice.md'
      - Backend:
        - Django:
          - Django: 'code/web/backend/django/django.md'
          - Principiante: 'code/web/backend/django/django-principiante.md'
          - Intermedio: 'code/web/backend/django/django-intermedio.md'
          - Avanzado: 'code/web/backend/django/django-avanzado.md'
  - Software:
    - Linux:
      - Fecha y Hora: 'sw/linux/linux-fecha-hora.md'
      - Ficheros: 'sw/linux/linux-ficheros.md'
    - Redes:
      - Linux: 'sw/redes/redes-linux.md'
      - SSH: 'sw/redes/redes-ssh.md'
      - iptables: 'sw/redes/redes-iptables.md'
      - IPv6: 'sw/redes/redes-ipv6.md'
    - Terminal:
      - Bash: 'sw/terminal/terminal-bash.md'
      - tmux: 
        - Comandos: 'sw/terminal/tmux/tmux-comandos.md'
        - Customización: 'sw/terminal/tmux/tmux-customizar.md'
      - ZSH: 'sw/terminal/terminal-zsh.md'
  - Hardware:
    - Micropython: 'hw/upython/upython-informacion.md'
    - Platformio: 'hw/pio/pio-informacion.md'
  - IoT:
    - MQTT:
      - MQTT: 'iot/mqtt/mqtt.md'
      - Hola mundo: 'iot/mqtt/mqtt-hello-world.md'

# 6. Google Analytics
#google_analytics:
#  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
#  - auto

# 7. Configuración del tema
theme:
  name: material
  # Color - Fuentes - Lenguaje
  palette:
    primary: green
    accent: pink
  font:
    text: Roboto
    code: Roboto Mono
  #logo: img/favicon.png
  #favicon: img/favicon.png
  language: es
  # Página 404
  static_templates:
    - 404.html
  # No incluir los JavaScript de MkDocs
  #include_search_page: false
  #search_index_only: true

# 8. Extensiones
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      linenums: true
      # guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# 9. Necesario para la extensión pydownx.arithmatex
extra_javascript:
  # Este fichero es opcional y solo si se quiere sobreescribir la configuracion del plugin
  #- js/extra.js
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML

# 10. Plugins
plugins:
  - search
  - minify:
      minify_html: true
